### ISSUE TITLE
GetObjectProperty does not work for properties in collection format

### ISSUE THREAD

**Issue by everton3x** [gabrielrcouto/php-gui#110]
I am trying to implement _TFileNameEdit_ and I encountered problems using the _DialogFiles_ property to return the selected files, regardless of whether or not the _ofAllowMultiSelect_ is used.

_TFileNameEdit.DialogFiles_ seems to return a string collection with the name of the selected files. The return type is _TStrings_.

From what I saw in the source code in Lazarus, _TIpcThread.GetObjectProperty_ always returns a string, but in the specific case the conversion done by _VarToStr (propertyValue)_ is not returning anything.

In addition could you tell me the way to fix this, since _TFileNameEdit_ only provides that property to access all the selected files.

**Comment by reisraff** [comment]
Please, create a PR with the code you have done, so I'll reproduce here, to understand what is happening, so then I tell you if I discover, what you need do.

**Comment by reisraff** [comment]
I created a PR in your fork repository with some changes for you continue.

https://github.com/everton3x/php-gui/pull/1/files

**Comment by reisraff** [comment]
@gabrielrcouto I guess it can be closed... If you give me access in this repository I can help you manage it.

**Comment by everton3x** [comment]
Thanks to @reisraff's help I was able to implement TFileNameEdit.

Basically, the GetObjectProperty has modified the IF / ELSE that identifies whether the property value is integer or string to also identify if the calling property is TFileNameEdit.DialogFiles.

I still find it interesting to think of a generic way of finding property values in Array format.

I'm going to start studying Free Pascal to come up with a solution.
