### ISSUE TITLE
How to close main window, and some advice.

### ISSUE THREAD

**Issue by xpader** [gabrielrcouto/php-gui#114]
I used

`$closeButton->on('click', function() use ($application) {
	exit();
});`

to close the window, the php process is exit, but the window is still exists.
and a little time later, some error happend.

And hope have some feature to use xml file to create ui.

**Comment by alrik11es** [comment]
I've discovered looking at the code that:
```php
$application->sendCommand("exit", [], function () {
});
```
Does the same thing. In fact this should be probably the "right way" of doing this.

But I have to say that the terminal doesn't exit using this. Not closing also when exiting the window clicking on the [X] button.

Thats why your solution works best and seems the best right now.

**Comment by reisraff** [comment]
https://github.com/gabrielrcouto/php-gui/blob/master/src/Application.php#L343

**Comment by alrik11es** [comment]
So `$application->terminate()` thanks for pointing out.

**Comment by xpader** [comment]
I changed code to this:
$closeButton->on('click', function() use ($application) { $application->terminate(); });
When click close button, the console was closed, but phpgui window still not close, and when click another button, the window closed.

**Comment by reisraff** [comment]
Hey guys, I found a bug about this issue, so... with this patch #118 it is fixed
