### ISSUE TITLE
Centering the form in screen dynamically

### ISSUE THREAD

**Issue by alrik11es** [gabrielrcouto/php-gui#119]
Is it possible with PHP-GUI? How can I access such data like screen size, mouse position?

**Comment by reisraff** [comment]
You can get the application windows size doing:

```php
<?php

$application->getWindow()->getHeight();
$application->getWindow()->getWidth();
```

And also the window position with getLeft and getTop methods but the mouse position I guess we still can not retrieve it.

**Comment by alrik11es** [comment]
Thanks @reisraff. I really think this library is a great improvement to the PHP world. Keep up the great work.
