### ISSUE TITLE
Bug: Gui\Ipc\Receiver 

### ISSUE THREAD

**Issue by reisraff** [gabrielrcouto/php-gui#12]
sometimes the $application->process->stdout wait for a some data length to write, and with it, the Receiver::onData() can't to process the message because sometimes the message came that way:

```json
{"id": 6, "result": 2}Get: {"callback":{},"id":7,"method":"setObjectEventListener","params":[2,"onclick"]}
```

As you can see, after the end of the 1st JSON is the letter "G", and it's beeing sent by the lazaruz binary. 

So, with the following condition the PHP goes inside the if statement, but in the next instruction the json can not be decoded.

```php
if ($data[0] === '{' && $data[strlen($data) - 1] === '}') {
    $message = json_decode($data);
// ...
```

I can see 2 way to solve it;

1. to send by lazarus a custom json with the key "received" or "debug" or something like this, and in receiver ignore all jsons that come with this key.

2. stop to send messages that aren't part of the communication

PS: with this bug the Gui\Ipc\CommandMessage callback doesn't work
--
And as the process->stdout works that way, I mean that sometimes the Receiver::onData() can receive 2 or more jsons, and it MUST be splitted. and it is not being done.

**Comment by reisraff** [comment]
And as the process->stdout works that way, I mean that sometimes the Receiver::onData() can receive 2 or more jsons, and it MUST be splitted. and it is not being done.

**Comment by gabrielrcouto** [comment]
I think we need to do on PHP the same message splitting which was implemented on Lazarus.
And I agree to use {"method":"debug"} for Lazarus debugging messages.
