### ISSUE TITLE
php7.2 Fatal error

### ISSUE THREAD

**Issue by xiagg** [gabrielrcouto/php-gui#136]
Fatal error: Cannot use Gui\Components\Object as Object because 'Object' is a sp
ecial class name in D:\phpgui\vendor\gabrielrcouto\php-gui\src\Application.php o
n line 5

Not urgent,but would be a problem.

big thanks for this project!

**Comment by reisraff** [comment]
https://github.com/gabrielrcouto/php-gui/issues/129
