### ISSUE TITLE
Can't run in php7.2 environment

### ISSUE THREAD

**Issue by Elevioux** [gabrielrcouto/php-gui#143]
Trying run the example code in php7.2 environment, got this error

PHP Fatal error:  Cannot use Gui\Components\Object as Object because 'Object' is a special class name in D:\phpcli\gui\vendor\gabrielrcouto\php-gui\src\Application.php on line 5

Things are fine in 7.1

**Comment by aolko** [comment]
#136

**Comment by andreybolonin** [comment]
@Elevioux user `dev-master` version.
This pr is merged https://github.com/gabrielrcouto/php-gui/pull/134

**Comment by renatosc** [comment]
I confirm the dev-master works.

If you are using composer, make sure your composer.json is loading the library as:
`"require": {
        "gabrielrcouto/php-gui": "dev-master"
    }`

**Comment by reisraff** [comment]
The new tag solve this problem
