### ISSUE TITLE
How do I display a jpg image in the window?

### ISSUE THREAD

**Issue by renatosc** [gabrielrcouto/php-gui#145]
How can I display a jpg/png image inside a Window? Do I need to read the image file as a binary array and use Canvas?

**Comment by reisraff** [comment]
For now its just possible with canvas, we should add a new component to load a jpg/png/etc... using http://lazarus-ccr.sourceforge.net/docs/lcl/graphics/tpicture.html.

**Comment by reisraff** [comment]
#158
