### ISSUE TITLE
How to run app without docker?

### ISSUE THREAD

**Issue by CzarnyZajaczek** [gabrielrcouto/php-gui#149]
./lazarus/linux-docker.sh
standard_init_linux.go:178: exec user process caused "exec format error"

but I have only binary compiled for my architecture, and when I run it directly it displays window (without widgets of course)

**Comment by CzarnyZajaczek** [comment]
update

just changed `phpgui-x86_64-linux` in file src/Application.php to `phpgui-i386-linux`
and it now works (I'm currently using i686 system architecture on AMD64 computer to be able to temporarily run the same system installation on my other old PC which is i686)

**Comment by reisraff** [comment]
#150
