### ISSUE TITLE
Cannot use Gui\Components\Object as Object because 'Object' is a special class name

### ISSUE THREAD

**Issue by CViniciusSDias** [gabrielrcouto/php-gui#152]
When trying to run the example with PHP 7.2 on Windows  10 I receive the following error:
PHP Fatal error:  Cannot use Gui\Components\Object as Object because 'Object' is a special class name in {project-path}\vendor\gabrielrcouto\php-gui\src\Application.php on line 5

Fatal error: Cannot use Gui\Components\Object as Object because 'Object' is a special class name in {project-path}\vendor\gabrielrcouto\php-gui\src\Application.php on line 5

**Comment by reisraff** [comment]
The fix is patched on master, not yet tagged.
