### ISSUE TITLE
New release plz

### ISSUE THREAD

**Issue by jawira** [gabrielrcouto/php-gui#153]
A lot of issues were solved since the first release from **2016** 😞, I'm thinking specially about issue #136.
So, could you please launch a new release?, it could be v0.1.1 for example.
 
Thanks a lot for your amazing job 👍

**Comment by insign** [comment]
#134 didnt solve this?

**Comment by jawira** [comment]
> #134 didnt solve this?

Well, yes it did. 
But when I do a `composer update` changes are never pulled.

**Comment by reisraff** [comment]
On it!

**Comment by reisraff** [comment]
https://github.com/gabrielrcouto/php-gui/releases/tag/v0.1.1
