### ISSUE TITLE
Table Component Not Work

### ISSUE THREAD

**Issue by lafraga93** [gabrielrcouto/php-gui#162]
Thanks for implement table component, but this element is not created when event handler is call and can't show errors in console output.

I try debug, but unsuccessful...

I'm running on Windows10 x64. This can help identify a problem?

**Comment by reisraff** [comment]
It is because is not released yet, if you are forking the master branch, take in mind, that is not the stable version, looking at the git log I see that there is no compilation for windows after this component implementation.

That is, you need compile before use this new component.

**Comment by lafraga93** [comment]
Thanks, it works! I need to pull request with changes after compile?  I fork the master branch because I had problems on event click in the stable version.

**Comment by reisraff** [comment]
would be good, we haven't implemented yet the automatic compilation, since we need to ask for some people to compile for us on windows/mac etc..
