### ISSUE TITLE
*bars and other components

### ISSUE THREAD

**Issue by feamsr00** [gabrielrcouto/php-gui#172]
So! If the Lazarus LCL includes such timeless classics as MenuBars, ToolBars, and StatusBars (oh my!), how do we expose them on the PHP side?

**Comment by reisraff** [comment]
It's about implement all them in this file https://github.com/gabrielrcouto/php-gui/blob/master/lazarus/unitipcthread.pas over the IPC protocol.

**Comment by feamsr00** [comment]
Hi @reisraff. Thanks for getting back to me. You said "It's" about to implement them all. Whats "Its"?

**Comment by reisraff** [comment]
you should implement... those LCL.

**Comment by feamsr00** [comment]
I could consider that, indeed. That file seems to have some, but not a heck of a lot of comments. Is there anywhere that has a write up on how to dive into that?

**Comment by reisraff** [comment]
no I think, you should read the code, and try yourself, what you can do, is
search for some "implementation commit" of some LCL component and learn
with this.

**Comment by reisraff** [comment]
like this one: https://github.com/gabrielrcouto/php-gui/commit/1675096062f2cad695e914a805c9c43bb23004b0
