### ISSUE TITLE
Multiple Continuos IPC messages performance

### ISSUE THREAD

**Issue by gabrielrcouto** [gabrielrcouto/php-gui#18]
In example "05-canvas" is possible to see what happens when multiple IPC messages are sent. After a while, the messages are ignored by Lazarus, the GUI still works, but don't receive anymore new IPC messages (still sends). 

Can be:
- The buffer size
- The JSON performance
- The Lazarus thread reading performance
- The need of a protocol like TCP, based on a pool (PHP only sends message 2 after the confirmation of message 1).

**Comment by reisraff** [comment]
It is a bug that PR #21 fixes.

**Comment by gabrielrcouto** [comment]
After some rafactor, I found the answer: this bug is about the buffer size. 

On linux, the std pipes have only 65536 bytes (OSX 16384 bytes). We will need to buffer on each side (like a queue), PHP and Lazarus, and send the messages in slices, waiting for the other side to reply "Ok, I gotted, you can send more data". Unfortunately this will slow down the communication.

**Comment by gabrielrcouto** [comment]
Ok, implemented a solution on PHP side. Works like a charm :smile:

**Comment by reisraff** [comment]
:+1:
