### ISSUE TITLE
Autofocus of window would be great

### ISSUE THREAD

**Issue by rogeriopradoj** [gabrielrcouto/php-gui#23]
Running examples I realize that the window php-gui opens are hidden behind other applications, I guess the issue is because of Autofocus not being used yet.

**Comment by reisraff** [comment]
See this PR #26

**Comment by rogeriopradoj** [comment]
Not working on OS X 10.10.5. The window still hidden.

**Comment by reisraff** [comment]
@gabrielrcouto do you have some idea of how do this to work in OSX 10.10.5?

**Comment by pokemaobr** [comment]
People, the commands on buttons returned to fail in Windows. I click on the buttons and have no reason. When I close the window all the "callObjectEventListeners" appear on console.

**Comment by pokemaobr** [comment]
But the focus is working

**Comment by rogeriopradoj** [comment]
@pokemaobr , it's the same that is happening to me on windows.

>People, the commands on buttons returned to fail in Windows. I click on the buttons and have no reason. When I close the window all the "callObjectEventListeners" appear on console.

**Comment by gabrielrcouto** [comment]
@pokemaobr: Thank you, I found the bug. Could you, please, test again?
@rogeriopradoj: Unfortunately, auto focus on OSX will not work. OSX just do the auto focus when you open an app using "open nameOfThe.app", but, to be able to communicate with the process via stdin/stdout, we need to open the app using the binary (it's inside the .app).
