### ISSUE TITLE
No action in buttons on Windows

### ISSUE THREAD

**Issue by pokemaobr** [gabrielrcouto/php-gui#24]
In Windows the Lazarus doesn't execute the actions.

**Comment by gabrielrcouto** [comment]
Ok, I found the bug. On Windows, the fread to stdout is blocking, and the PHP will hangs after the first fread.

The React\Stream uses fread to handle data. I will fork the React\Stream project, apply a patch and update our composer.json. Unfortunately, I think the core team from React\Stream will not accept my solution as a PR.

@pokemaobr: Could you please do a test? Edit your 'vendor/react/stream/src/Stream.php' file, and replace the content of 'handleData' function to the content below.

```php
public function handleData($stream)
{
    $read = [$stream];
    $write = [];
    $except = [];

    $result = stream_select($read, $write, $except, 0);

    if ($result === false) throw new Exception('stream_select failed');
    if ($result === 0) return false;

    $status = fstat($stream);

    if ($status['size'] > 0) {
        $size = $status['size'];

        if ($size > 1) {
            $size -= 1;
            $data = stream_get_contents($stream, $size);
            $data .= stream_get_contents($stream, 1);
        } else {
            $data = stream_get_contents($stream, 1);
        }

        $this->emit('data', array($data, $this));
    }
}
```

@reisraff: Do you see another way than forking the React\Stream?

**Comment by reisraff** [comment]
I see 4 options

1. Refactor the React\ChildProcess\Process and all mentions of React\Stream\Stream abstracting it all.
2. Try to send a PR
3. Open a github team for the PHP-GUI, and do a fork there.
4. As we talked, to pause the stream and do something like we made with waitingMessage on Receiver.

**Comment by pokemaobr** [comment]
@bob @reisraff Doing the change @bob as proposed, the commands on Windows buttons come back to life :) What do we do now?

**Comment by gabrielrcouto** [comment]
@pokemaobr: I will implement the solution 4, as proposed by @reisraff :smile: 
After this, we need to test on Windows with PHP 5.6 and PHP 7.
