### ISSUE TITLE
Call an object method

### ISSUE THREAD

**Issue by gabrielrcouto** [gabrielrcouto/php-gui#3]
Sometimes we will need to call a object method, like ScrollBy(DeltaX, DeltaY) for scrolling a text field.

**Comment by gabrielrcouto** [comment]
After searching a lot of RTTI on Lazarus:
- Only published methods can be found via RTTI :cry: 
- The TVmt doesn't contains the name of other methods
- You can see the addess of a method (like the Hide method): inttostr(longint(@objArray[1].Hide))
- The TComponent methods addess will be the same for all objects

**Comment by gabrielrcouto** [comment]
The easiest solution is to do a big switch and call the methods manually, without reflection.

**Comment by reisraff** [comment]
How many methods do you think the LCL have?

**Comment by reisraff** [comment]
#17

**Comment by gabrielrcouto** [comment]
Ok, we will go without reflection. :cry:
