### ISSUE TITLE
Create an object for radio/select item

### ISSUE THREAD

**Issue by reisraff** [gabrielrcouto/php-gui#33]

**Comment by Simplesmente** [comment]
But these class don't ready done in Components ?

**Comment by reisraff** [comment]
Hey @Simplesmente, Gui\Components\Radio and Gui\Components\Select already exists, but Item not yet.

https://github.com/gabrielrcouto/php-gui/blob/master/src/Components/Radio.php#L32

As you can see in the link we're checking if is string and something like this. IMO should be better that each array item must be and Gui\Components\Item for example.

**Comment by alexmsilva** [comment]
@gabrielrcouto I guess you can close this issue :-)

**Comment by Simplesmente** [comment]
Yes, of course.
