### ISSUE TITLE
Screen freezing

### ISSUE THREAD

**Issue by marabesi** [gabrielrcouto/php-gui#41]
Hello guys,

I've been using Ubuntu for a while and I tried to run the code shown in README.md file but my screen just freeze when I run it.

```
<?php
require 'vendor/autoload.php';

use Gui\Application;
use Gui\Components\Button;

$application = new Application();

$application->on('start', function() use ($application) {
    $button = (new Button())
        ->setLeft(40)
        ->setTop(100)
        ->setWidth(200)
        ->setValue('Look, I\'m a button!');

    $button->on('click', function() use ($button) {
        $button->setValue('Look, I\'m a clicked button!');
    });
});

$application->run();
```

My O.S : Ubuntu 14.04 

any ideas ?

**Comment by reisraff** [comment]
which is your php version? and the window appears?

**Comment by ricardofontanelli** [comment]
@marabesi I'm running it ok in my Ubuntu Desktop 14.04 LTS. It is showing you the execution log on terminal?

**Comment by marabesi** [comment]
my php version is 5.5.9

**Comment by pokemaobr** [comment]
Requirements

The following PHP versions are supported:

PHP 5.6
PHP 7
HHVM
And OS:

Linux x64
Windows x64
Mac OSX (tested on 10.10.x and 10.11.x)

**Comment by marabesi** [comment]
@ricardofontanelli I can't access  my terminal after execute the php script. I have to reboot to get my machine working again , thought, I haven't tried php 7. This error can occur because my php version is old

**Comment by marabesi** [comment]
@pokemaobr yeap that is it, my bad. Thanks folks : D

**Comment by leonnleite** [comment]
@marabesi PHP versions are supported:
PHP 5.6
PHP 7
HHVM

the problem is possibly your version
