### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by ionas** [gabrielrcouto/php-gui#45]
Which there was an easy way to get a PHP+SQLITE stack up and running on iOS ;)
Then one could deploy the same app to clients as to the server (distributed software system)

**Comment by ionas** [comment]
I know its OffTopic so closing :p

**Comment by gabrielrcouto** [comment]
It will be amazing! Lazarus can compile for iOS, we just need a way to pack everything together.

**Comment by ionas** [comment]
That would be very cool. I don't know about the state of a bundled sql databased, sqlite will be sufficient for most stuff.
