### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by HuanMeng0** [gabrielrcouto/php-gui#53]
I'm currently using PHP-GUI wrote a program, how to compile it into exe?

**Comment by gabrielrcouto** [comment]
Thank you for using the project :smile: 

Sorry, but PHP-GUI doesn't provide a way to do that.

If you want to distribute the application for "non PHP developers", you will need to use a "packer" (and it can be easily another project). Today, you can generate a .phar for each platform (with just the binaries for each platform) using something like https://github.com/box-project/box2. Of course, you will need to send the PHP binary or the user will need to have it installed.

If you want to distribute for PHP developers, just put on packagist, and a single composer require will solve all the dependencies :-)
