### ISSUE TITLE
Installation failure from Composer

### ISSUE THREAD

**Issue by tfont** [gabrielrcouto/php-gui#55]
> composer require gabrielrcouto/php-gui

You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Using version ^0.1.0 for gabrielrcouto/php-gui
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for gabrielrcouto/php-gui dev-master -> satisfiable by gabrielrcouto/php-gui[dev-master].
    - Can only install one of: gabrielrcouto/php-gui[v0.1.0, dev-master].
    - Installation request for gabrielrcouto/php-gui ^0.1.0 -> satisfiable by gabrielrcouto/php-gui[v0.1.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by gabrieljmj** [comment]
Did you tried update your Composer?
```
$ composer self-update
```

**Comment by tfont** [comment]
Yes. This error was taken after!

**Comment by tfont** [comment]
After a bit of detail digging, I realized that I '_followed_' the instructions too direct.

Instead of running "composer require gabrielrcouto/php-gui" which was what I did at first, I ran "composer update" within the directory **after** retrieving the GIT repo directly (using GIT).

Also in addition, I removed dev from squizlabs/php_codesniffer: "2.0.*@dev" to "2.0.*"

And all worked fine :+1:
