### ISSUE TITLE
Protocol

### ISSUE THREAD

**Issue by darkphase** [gabrielrcouto/php-gui#72]
Good Idea.. 
Looks similar to GTKserver Project. ( so why restrained with just PHP, right? )
Seperating GUI and App Logic should eliminate UI hangout problems inherent in PHP GUI solutions. ( unless protocol is "sync". )
I compiled the executable but...
Is there a protocol documention? ( So one may write his/her own proxy libs. )
How we talk to executable? (I am illiterate in Pascal) 

Keep up the excellent work...

**Comment by qbitza** [comment]
> Is there a protocol documention? ( So one may write his/her own proxy libs. )
The Protocol is documented here: https://github.com/gabrielrcouto/php-gui/blob/master/PROTOCOL.md

> How we talk to executable? (I am illiterate in Pascal)
The executable listens on stdin for JSON commands.

**Comment by darkphase** [comment]
Thanks,
Is is possible to create and destroy windows?

**Comment by gabrielrcouto** [comment]
Thank you very much @darkphase. When I was doing my research (before the implementation), I found the GTKserver, and it was an inspiration. 

As @qbitza said, the protocol is documented, and it uses JSON messages (based on JSON RPC) via STDIN/STDOUT. I'm testing a better protocol (#43), and JSON could be replaced by a binary protocol.

I agree that the GUI can be used by another languages, but my focus is to first optimize the PHP <-> Lazarus communication.
