### ISSUE TITLE
Run without console

### ISSUE THREAD

**Issue by pyrkamarcin** [gabrielrcouto/php-gui#76]
Is it possible to run applications written without opening the console in the background?

**Comment by rodrigowbazevedo** [comment]
You can execute with nohup

**Comment by JetAlone** [comment]
Yeap.
But I don't know a Win methods. I check all like "START /B" and none gave the desired outcome.

**Comment by gabrielrcouto** [comment]
We need a better way to do that. I'm thinking to enable the Lazarus application to start PHP if it is started by the user (and not by PHP). This is a step to have a "packer" for the GUI application.

**Comment by qbitza** [comment]
See PHP4Lazarus project - https://github.com/rnapoles/PHP4Lazarus

**Comment by fabioassuncao** [comment]
@gabrielrcouto, a packer will be of great importance for apps distributions with PHP GUI. It's very exciting! :D

**Comment by JiaFeiX** [comment]
@JetAlone I use some BAT file start examples,  check this https://github.com/XunCCC/PHP-GUI-WinTest      

BAT files  is not the right way, and I hope  the "packer" for the GUI application.  @gabrielrcouto

**Comment by JetAlone** [comment]
@JiaFeiX  YEAP! This is best method. In what language are binaries? Can you publish as open source?

**Comment by JiaFeiX** [comment]
@JetAlone    https://redmine.lighttpd.net/projects/1/wiki/tutoriallighttpdandphp   It's LightHttp team's little tool , in the end of the page  .   I don't have source , it should be C

**Comment by JiaFeiX** [comment]
http://superuser.com/questions/140047/how-to-run-a-batch-file-without-launching-a-command-window

**Comment by forsona** [comment]
I use 'RunHiddenConsole.exe' to hide the console, but a thread  named 'conhost.exe' still running in the background( if I run it again, another thread appears ). So I want to know how to start an event before close the window,  in that case, I can kill it by using some command
I try by using "$app->on('exit',.....)", but nothing happened -. -||

**Comment by PeratX** [comment]
Use a VBS file to start the php.

Set ws = CreateObject("Wscript.Shell")
ws.run "php a.php",vbhide

**Comment by reisraff** [comment]
@forsona 
> I use 'RunHiddenConsole.exe' to hide the console, but a thread named 'conhost.exe' still running in the background( if I run it again, another thread appears ). So I want to know how to start an event before close the window, in that case, I can kill it by using some command
I try by using "$app->on('exit',.....)", but nothing happened -. -||

Now it works with my PR https://github.com/gabrielrcouto/php-gui/pull/108
