### ISSUE TITLE
Add vendor folder in "src" to correct the PSR-0

### ISSUE THREAD

**Issue by ByBrunoSan** [gabrielrcouto/php-gui#77]
In **PSR-0** a fully-qualified namespace and class must have the following structure:
` \<Vendor Name>\(<Namespace>\)*<Class Name>`

And the current structure of **php-gui** don't have a vendor name. Why?

**Comment by gabrielrcouto** [comment]
Because it's not PSR-0, it's PSR-4, you can see this into composer.json:

```json
"autoload": {
        "psr-4": {
            "Gui\\": "src/",
            "Test\\": "test/"
        }
    }
```
