### ISSUE TITLE
runing on ARM

### ISSUE THREAD

**Issue by lmanliang** [gabrielrcouto/php-gui#84]
Can runing ARM ?
example ArchLinux-arm

**Comment by leledumbo** [comment]
As far as source code is concerned, yes. It doesn't use any platform specific code so it should be compileable on all platforms supported by Free Pascal. Just tested compiling for ARMHF (Raspberry Pi).

**Comment by reisraff** [comment]
@gabrielrcouto I guess you can add to the README and explanation like 

> As far as source code is concerned, yes. It doesn't use any platform specific code so it should be compileable on all platforms supported by Free Pascal. Just tested compiling for ARMHF (Raspberry Pi).

;)

**Comment by lmanliang** [comment]
thx. i well to try it for arm.
