### ISSUE TITLE
TOpenDialog method

### ISSUE THREAD

**Issue by HackMemory** [gabrielrcouto/php-gui#85]
Hello! I rebuild the lazarus and I added the TOpenDialog.
`RegisterClass(TOpenDialog);`

And when I "Execute", its not working
I'm calling like this:
`$this->call('execute', []);`

Where is my mistake?
Sorry for my English!

**Comment by reisraff** [comment]
@akper can you show you commit diff? so that way we can see what is happening :wink:

**Comment by styks1987** [comment]
I'm interested in the dialog method as well do you have plans to implement this? If I wanted to implement it do you have any things you have thought through on that subject? I assume there is a reason there is no component for it already

**Comment by everton3x** [comment]
@styks1987, I'm working on something similar: TFileNameEdit. I also have a PR with the TDirectoryEdit implementation, but I'm still struggling with Travis-CI to fix minor errors in formatting the code.

**Comment by styks1987** [comment]
@everton3x - Hey great job. Thank you. Just compiled and tested that out. Looks good so far.

**Comment by reisraff** [comment]
Its already on master #109
